### ISSUE TITLE
Node 15+ unsupported

### ISSUE THREAD

**Issue by kacperzuk-neti** [liberland/liberland_frontend#9]
Running with node 18 (current LTS):
* complains about ERR_OSSL_EVP_UNSUPPORTED (see details in v17 changelog: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V17.md#17.0.0). This can be worked around with env option `NODE_OPTIONS=--openssl-legacy-provider`.
* fails to build sass, as node-saas v4.14.1 that's used only supports node up to v14 ( https://github.com/sass/node-sass/releases/tag/v4.14.1 ).

Both of these seem like something that can be fixed by updating deps.

**Comment by mmlado** [comment]
I would like to take this ticket. I've managed to start it on node v18.15.0. It compiles and can be started. Still need to set up the whole system completely as I'm running only this repository for now. I've also updated all libraries to the latest ones, except Ethers which released a beta version 6 that has issues.
It looks like it's not a high priority.

**Comment by mmlado** [comment]
I'm not able to continue with this. The readme is missing some parts and I can't setup the whole system for testing.
I can't find repositories:
- The env file contains a connection to a local Hardhat instance.
- It mentions SSO
- It mentions API

It stats I should run yarn in the backend. Tried in root folder, but it can't find anything.

**Comment by kacperzuk-neti** [comment]
Fixed in #128
